# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_data', '0002_auto_20171118_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
