# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('symbol', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('time_start', models.DateField(blank=True, null=True)),
                ('time_end', models.DateField(blank=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount.Currency')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_from_city', to='geo_data.City')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_to_city', to='geo_data.City')),
            ],
        ),
    ]
